package co.payrail.attendance_srv.auth.dto.enums;

public enum PermissionEnum {
    ADD_USER_PERMISSION,
    EDIT_USER_PERMISSION,
    VIEW_USER_PERMISSION,
    DELETE_USER_PERMISSION,
    UPDATE_USER_PERMISSION,
    VIEW_RECRUITMENT_PERMISSION,
    EDIT_RECRUITMENT_PERMISSION,
    DELETE_RECRUITMENT_PERMISSION,
    ADD_RECRUITMENT_PERMISSION,
    VIEW_LEARNING_RESOURCE_PERMISSION,
    DELETE_LEARNING_RESOURCE_PERMISSION,
    ADD_LEARNING_RESOURCE_PERMISSION,
    VIEW_PAYROLL_PERMISSION,
    EDIT_PAYROLL_PERMISSION,
    ADD_PAYROLL_PERMISSION,
    UPDATE_PAYROLL_PERMISSION,
    DELETE_PAYROLL_PERMISSION,

    EDIT_SECURITY_DATA_PERMISSION,
    ADD_SECURITY_DATA_PERMISSION,
    UPDATE_SECURITY_DATA_PERMISSION,
    DELETE_SECURITY_DATA_PERMISSION,

    VIEW_SECURITY_DATA_PERMISSION,

    EDIT_TASK_PERMISSION,
    ADD_TASK_PERMISSION,
    UPDATE_TASK_PERMISSION,
    VIEW_TASK_PERMISSION,
    DELETE_TASK_PERMISSION
}
